theme = "hugo-casper3"
baseURL = "https://chengshengblog.netlify.app/"
languageCode = "en-us"
title = "Chengsheng's Blog" 
googleAnalytics = "UA-178433381-2"

[params]
    title = "Chengsheng's Blog"
    author = "Chengsheng Deng"
    description = "Love Data, Tech, Photography and a diehard Laker's fan"
    copyright = ""
    copyright_link = "" 
    
[params.social]
        title = "Links"
 [[params.social.list]]
        class = "fab" 
        icon = "fa-twitter" 
        url = "https://twitter.com/KingDylanDeng"
        title = "Twitter"  
        
[[params.social.list]]
        class = "fab"
        icon = "fa-github"
        url = "https://github.com/ChengshengDeng"
        title = "GitHub" 
        