---
title: 'Define Yourself '
author: Chengsheng Deng
date: '2020-09-16'
slug: define-yourself
categories: []
tags:
  - Product
feature_image: ''
---
## Tell Me a Bit About Yourself </br> 

* This is an opportunity to connect your experience with the job you’ re interviewing for </br>   

* This is not a time to just read off your resume or blab about your personal life </br> 

* Pick out a few of the key things you ‘d like your interviewer to know about you.  </br> 

### Example Answer </br> 

Interviewer: Tell me a bit about yourself </br> 

Candidate : </br> 

Sure, I’d love to.
I’m currently a PM with MapSign, where I have been for the last two years. </br> 

I got into product management by accident, but found that I loved working with customers. A lot of people see technology as forcing complexity into their lives, but I don’t think it has to be that way. I like listening to customers, understanding exactly what their issues are, and figuring out how technology can simplify their lives.</br> 

After I graduated from college, I joined a small startup called MealRight as a software engineer. We were doing okay, but it just didn’t look like we were getting that hockey stick growth that everyone talks about. </br> 

I knew a bit about the restaurant industry from my family’s restaurant growing up, and I proposed pivoting to focus on giving restaurants more visibility into their suppliers. I talked with a bunch of restaurants to validate this problem, and successfully convinced the team to shift gears. </br> 

I stepped in as product manager where I stayed for several years, eventually leading a team of four PMs. </br> 

I’m currently a PM with MapSign, where I manage the personalization features. </br> 

I recently launched a feature which allows users to create their own maps. This was actually created on a whim for a hackathon I participated in, but it turned out that users really loved this. It allowed them to tell a “story.” Whereas previously people used our product mostly privately, now people were sharing their maps with family and friends. This has resulted in about a 15% increase in paying users. </br> 

I can go into more detail about my work at MapSign if you’d like. </br> 

Outside of work, I do a bit of coding for fun, participating in hackathons like the one I just mentioned. I also run a blog focused on the New York City music scene. I manage a team of ten writers—mostly college students, who are happy to write for free. We get about 200,000 visits per month. </br> 

I’m looking now for a role at an early-stage company where I’ll be able to take a single product from conception through to launch. I think my experience as a developer and as a PM who works cross-functionally will give me the background to work with, and even take on some of the responsibilities of, several other roles. That’s a lot of what interested me in this role; it’s at the perfect time for me to dive in, and it’s so closely related to the personalization work I’m doing right now






