---
title: Marketing Questions in Product Case
author: Chengsheng Deng
date: '2020-09-10'
slug: marketing-questions-in-product-case
categories: []
tags: []
feature_image: ''
---
Marketing questions are about product positioning, customers, and handling competition.  
Approach: 
Understand the Company: What are the company’s goals? What is its mission? What are its strengths and weaknesses? What threatens it? 
Understand the Competition: Break down the competition into segments. Who competes and in what market?(竞争对手是谁) How do they position themselves? How entrenched are they?(怎么巩固自己的位置) What are their strengths and weaknesses? 
Understand the Customers: Who are your customers? What desire or need is this product fulfilling?(这个产品满足了什么样的需求) What is the purchase/usage behavior like (one time only, repeated purchases, etc)? 
Understand the Landscape : Are there legal issues ? If you’re focusing on a particular region, what makes this region unique (e.g., frequent power outages)? What external forces are shaping your market? 
Market Your Product: Using the information you discussed in the earlier steps, decide on aspects such as the product and its positioning and how you will promote it (think about the customer decision making process here). Depending on your interviewer and the question, you might also want to discuss pricing and distribution. 
Example Question 

How would you market Windows Phone to developers (to encourage them to adopt it)? 
Well, let me first think a bit about what the market looks like right now, including the company, competition, customers, and general landscape.
As I understand it, Microsoft’s goal with respect to developers is to increase the number of high quality apps(微软公司的目标）. Windows Phone has fairly low market share right now, which is the main barrier to this happening: It’s just not interesting as a development platform(微软目前的困境/弱势). On the other hand, its strength is that Windows is dominant in the desktop market. (优势是在桌面端） This means ease of development and a strong brand name, at least in some senses. This is something for Microsoft to leverage.
The two biggest competitors are iPhone and Android. The iPhone is excelling in the higher-end market, which draws developers to the platform. The perception is that iPhone users download and spend more money on apps. The Android phone is interesting to developers due to its market share, but it can also be frustrating because of the large number of devices to support. （对于竞争对手的分析）
The customers, in this case, are the developers (指出客户是谁） – but obviously their decision will be somewhat based on what users want as well. There are a lot of types of developers: hobbyists, enterprise developers, startup developers, etc. Developers want a fast and easy language to build a product with and the ability to push out their product to as many users as possible.
The last thing to discuss, before going into a potential marketing plan, is the environment. We want to think about any trends that might open up holes in the market. One trend is the relative gap in the enterprise market, left by Blackberry’s decline. The iPhone and the Android have filled in that gap a bit, but there may still be some room there (particularly if you can get the backing of IT/system administrators). Another relevant part of the environment is the “diversity of phones from country to country. I don’t know the statistics on this, but I suspect there are some markets where iPhone and Android haven’t really dominated yet. (市场前景分析）
Now for the marketing plan: I think the key things we want to focus on are (1) making development on our platform as frictionless as possible; (2) ensuring the top apps on iPhone and Android also have a Windows Phone version; and (3) finding an opening in the market. Our positioning to developers is that we’ll make it easy to develop, maintain, and sell your app.
As far as making development easy: We already have a leg up here, in that many developers already know Windows development. We need to create an excellent set of tutorials and sample code to teach Windows Phone development. Let’s try, if possible, to offer amazing APIs that developers can stick in their app to build key functionality – like plug-and-play coding.
Additionally, because developers might struggle to find help on the web, we need to offer that help ourselves. We need to foster a community around Windows Phone development and offer free development support.
We need to tackle where iPhone and Android are weaker in a development environment. I haven’t done much mobile development myself, but I’ve heard iPhone developers complain about the insufficient data on tracking where downloads came from. Let’s excel in this area.
Ensuring that the top apps from both Android and iPhone are on Windows will take very proactive outreach. We need to track what apps are popular on those platforms. If they don’t have a Windows phone, give them one. We can possibly even help them with testing and support in order to bring the quality up to par, particularly if it’s just a single developer and not a full company or startup.
The biggest market opening is probably in the enterprise space, so this might be where we want to focus. We can push for enterprise developers and IT folk to specialize in developing and supporting Windows Phones; many of them already do Windows development, so this isn’t a big stretch. If we offer better tools to support their employees, this might encourage them to pick Windows over iPhone and Android for company-provided phones.
This plan is designed to communicate to developers that we have a full ecosystem of tools: tutorials, APIs, technical support, free devices, community, analytics, administration tools, etc. This will differentiate us in the eyes of developers; we’re putting them first to make us the fastest and easiest phone to develop for and support. 
Sample Questions 

What is a product you think is marketed well? How would you improve it?
How would you market Gmail in China?
How would you market the Android tablet?
What do you think of Google’s marketing for its social products? How would you improve it?
How would you market the next version of Windows?
How would you choose a market for expansion for Amazon Web Services?
Discuss how you think Whole Foods is currently marketed. What works well? What could they do better?
How would you market a mobile app to track weight, calorie consumption, and exercise?
How would you market Google Docs to schools?”
Describe how you would market a magazine subscription service for Kindle
