---
title: 'Leetcode SQL Interview Answer '
author: Chengsheng Deng
date: '2020-09-18'
slug: leetcode-sql-interview-answer
categories: []
tags:
  - SQL
feature_image: ''
---

**178 Rank Scores** 

* Level: Medium

SELECT Score, </br>
DENSE_RANK() OVER(ORDER BY Score DESC) 'Rank' </br>
FROM Scores  </br> 

* Please know the difference between `DENSE_RANK()` and `RANK()` 

**177 Nth Highest Salary** 

* Level: Medium </br>

CREATE FUNCTION getNthHighestSalary(N INT) RETURNS INT </br>
BEGIN </br>
  RETURN ( </br>
      SELECT DISTINCT a.Salary FROM (SELECT Salary, DENSE_RANK() OVER(ORDER BY Salary DESC) rnk FROM Employee) a </br>
      WHERE a.rnk = n </br>
  ); </br>
END 

* We use subquery here to get the rank of the salary with the decreasing order first. </br> 
* Then we select the `distinct` salary with the `WHERE` clause to filter the Nth rank  because we want the Nth highest salary. That would be a unique value. </br>   

**184 Department Highest Salary** 

* Level: Medium </br> 

WITH temp AS ( SELECT e.Name AS emp, e.Salary, e.DepartmentId, d.Name,   </br>
      RANK()OVER(PARTITION BY e.DepartmentId ORDER BY e.Salary DESC) rnk   </br>
      FROM Employee e  </br>
      JOIN Department d  </br>
      ON e.DepartmentId = d.Id )  </br>

SELECT Name AS Department, emp AS Employee, Salary </br>
FROM temp  </br>
WHERE rnk = 1  </br>
