---
title: 'Leetcode SQL Interview Question '
author: Chengsheng Deng
date: '2020-09-18'
slug: leetcode-sql-interview-question
categories: []
tags:
  - SQL
feature_image: ''
---

## RANK() & Window Function  



#### 178 Rank Scores  </br>

* Level: Medium </br> 

Write a SQL query to rank scores. If there is a tie between two scores, both should have the same ranking. Note that after a tie, the next ranking number should be the next consecutive integer value. In other words, there should be no "holes" between ranks. </br> 

+----+-------+</br>
| Id | Score |</br>
+----+-------+</br>
| 1  | 3.50  |</br>
| 2  | 3.65  |</br>
| 3  | 4.00  |</br>
| 4  | 3.85  |</br>
| 5  | 4.00  |</br>
| 6  | 3.65  |</br>
+----+-------+</br>

For example, given the above Scores table, your query should generate the following report (order by highest score): </br> 

+-------+---------+ </br>
| score | Rank    | </br>
+-------+---------+ </br>
| 4.00  | 1       | </br>
| 4.00  | 1       | </br>
| 3.85  | 2       | </br>
| 3.65  | 3       | </br>
| 3.65  | 3       | </br>
| 3.50  | 4       | </br>
+-------+---------+ </br>

Important Note: For MySQL solutions, to escape reserved words used as column names, you can use an apostrophe before and after the keyword. For example 'Rank'.</br> 

*Answer* : https://chengshengblog.netlify.app/post/leetcode-sql-interview-answer/  

#### 177 Nth Highest Salary </br> 

* Level: Medium </br>  

Write a SQL query to get the nth highest salary from the Employee table. </br> 

+----+--------+ </br> 
| Id | Salary | </br>
+----+--------+ </br>
| 1  | 100    | </br> 
| 2  | 200    | </br>
| 3  | 300    | </br>
+----+--------+ </br> 

For example, given the above Employee table, the nth highest salary where n = 2 is 200. If there is no nth highest salary, then the query should return null. </br> 

+------------------------+ </br> 
| getNthHighestSalary(2) | </br> 
+------------------------+ </br> 
| 200                    | </br> 
+------------------------+ </br>  

*Answer* : https://chengshengblog.netlify.app/post/leetcode-sql-interview-answer/   </br> 

#### 184 Department Highest Salary  </br>

The Employee table holds all employees. Every employee has an Id, a salary, and there is also a column for the department Id. </br>

+----+-------+--------+--------------+ </br>
| Id | Name  | Salary | DepartmentId | </br>
+----+-------+--------+--------------+ </br>
| 1  | Joe   | 70000  | 1            | </br>
| 2  | Jim   | 90000  | 1            | </br>
| 3  | Henry | 80000  | 2            | </br>
| 4  | Sam   | 60000  | 2            | </br>
| 5  | Max   | 90000  | 1            | </br>
+----+-------+--------+--------------+ </br>

The Department table holds all departments of the company. </br>

+----+----------+ </br>
| Id | Name     | </br>
+----+----------+ </br>
| 1  | IT       | </br>
| 2  | Sales    | </br>
+----+----------+ </br> 

Write a SQL query to find employees who have the highest salary in each of the departments. For the above tables, your SQL query should return the following rows (order of rows does not matter). </br>

+------------+----------+--------+ </br>
| Department | Employee | Salary | </br>
+------------+----------+--------+ </br>
| IT         | Max      | 90000  | </br>
| IT         | Jim      | 90000  | </br>
| Sales      | Henry    | 80000  | </br>
+------------+----------+--------+ </br>

Explanation: </br>

Max and Jim both have the highest salary in the IT department and Henry has the highest salary in the Sales department. </br>

*Answer* : https://chengshengblog.netlify.app/post/leetcode-sql-interview-answer/   </br> 
